

# Chapter 1: Investigating object orientation effects across 18 languages

\bigskip
\bigskip
\bigskip


```{r}

# This chapter is rendered by 'main.Rmd'. Thus, it inherits all the 
# parameters set in 'main.Rmd' and the objects loaded therein 
# (although no objects are no objects are used in this chapter).

```


\begin{adjustwidth}{1.5cm}{1.5cm}

At the beginning of my PhD, I contributed to a study led by Dr. Sau-Chin Chen (from Tzu Chi University, in Taiwan) and coordinated by the Psychological Science Accelerator (study page available at https://psysciacc.org/002-object-orientation). In the present chapter, I describe this study and discuss several aspects.

\end{adjustwidth}

\bigskip
\bigskip
\bigskip


One of the seminal findings supporting the sensorimotor basis of conceptual processing was the object orientation effect. @stanfieldEffectImpliedOrientation2001 observed this effect in a sentence-picture verification task. On each trial of this task, participants first read a sentence such as ‘The eagle is in the nest’. On the next screen, they saw a certain picture and had to verify whether the protagonist of the sentence was present in the picture. Thus, following the previous example, if the picture showed an eagle, participants would click on the ‘yes’ button. The key manipulation of this paradigm, unbeknownst to participants, was that the protagonist shown in the picture could either match or mismatch the orientation that had been implied in the sentence. For instance, following the example sentence above, if participants saw an eagled perched on a branch, the orientation would be matched. If instead the eagle were flying, the orientation would be mismatched. The theory of embodiment in language comprehension sustains that people mentally simulate perceptual and motor features of meaning [@barsalouPerceptualSymbolSystems1999a; @pulvermullerWordsBrainLanguage1999]. Therefore, according to Stanfield and Zwaan, pictures with a mismatching orientation (compared to pictures with a matching orientation) would incur processing costs, as participants would need to adjust their mental simulation of the scene. This was indeed the result observed by Stanfield and Zwaan.

However, subsequent studies revisiting the object orientation effect revealed mixed results. The finding replicated more successfully in English than in other languages [@rommersObjectShapeOrientation2013; @kosterMentalSimulationObject2018; @chenDoesObjectSize2020; @zwaanRevisitingMentalSimulation2012; @dekoningMentalSimulationFour2017]. One of the non-replications received a response from @zwaanReplicationsShouldBe2014, who argued that the replication was underpowered---lacking a sufficient sample size---and pointed to several methodological differences with the original study. These comments are noteworthy, and will resonate throughout the present thesis.

@chenInvestigatingObjectOrientation2018a revisited the object orientation effect by conducting a large, crosslinguistic study (for materials and updates on this study, please see https://osf.io/e428p).^[Please note that the preprint of @chenInvestigatingObjectOrientation2018a mentions '14' languages but finally 18 languages were included.] The design comprised the classic sentence-picture verification task, with objects matching or mismatching the orientation implied in the preceding sentence on each trial. The sample size was far larger than the average in the field. English had 1,363 participants. The other languages had a minimum of 50 and a maximum of 262 participants. The results did not present a main effect of orientation match. Furthermore, the study also included an individual difference that measured participants’ ability to mentally rotate objects. The inclusion of such an individual difference in the model was motivated by previous suggestions that this ability could act as a confound, by interfering with the effect of interest [@chenInvestigatingObjectOrientation2018a]. Such a possibility was not too remote, according to recent research that has highlighted the role of participant-specific cognitive biases [@delucaRedefiningBilingualismSpectrum2019; @montero-melisConsistencyMotionEvent2021]. However, the mental rotation score was not found to predict the (non-significant) difference between the match and the mismatch conditions. 

Furthermore, the study of @chenInvestigatingObjectOrientation2018a was pioneering as it investigated the object orientation effect across 18 languages, including Arabic, Hebrew, Polish, Simplified Chinese and Turkish. While an initial analysis revealed a significant orientation match advantage in German, a follow-up analysis precluded this effect. Therefore, the effect was not significant in any of the 18 languages. 

The breadth of crosslinguistic variation deployed in this study constitutes a very novel contribution to the topic of conceptual processing. Precisely the scarcity of precedents makes such a crosslinguistic investigation challenging nowadays. Thus, we could now consider some desirable characteristics for future studies, such as the need to reach sufficient sample sizes in all languages. Determining a sufficient sample size will require a conservative power analysis that should itself be based on a sufficient amount of reliable data [@albersWhenPowerAnalyses2018]. Furthermore, to prevent the misinterpretation of crosslinguistic differences, all languages should have the same sample size. 

Last, for the longer term, it would be desirable to work towards a theory of crosslinguistic variation in conceptual processing, which would help in the design of studies and in the interpretation of any crosslinguistic differences. This goal will require research on the lexicosemantic and syntactic differences across languages that are relevant to the effect of interest in conceptual processing (in this case, the object orientation effect). In @chenInvestigatingObjectOrientation2018a, we outlined some typological differences across some of the languages examined; specifically, differences in the lexical encoding of motion [@verkerkCorrelationMotionEvent2014] and in the encoding of placement [@newmanCrosslinguisticOverviewPosture2002]. While this was hopefully a move in the right direction, I think that future empirical work with a crosslinguistic aspiration would necessitate further typological theory. This is very much uncharted territory in the topic of conceptual processing, so it is exciting but also uncertain. To help chart the course, the topic area of linguistic relativity is likely to contain useful resources and examples. For instance, @bernabeuMoreRefinedTypology2019 suggested that a novel typological classification of motion [@verkerkCorrelationMotionEvent2014] could be useful for the design of studies in linguistic relativity.

Three of the topics discussed in this chapter constitute key elements of the next chapter, which will describe Study 2. The first of these topics is the role of sensorimotor simulation in conceptual processing. The second topic is the role of individual differences. The third topic is the importance of statistical power. In addition to these topics, Study 2 will also incorporate the language system to the study of conceptual processing. Whereas sensorimotor simulation is characterised by detailed representations that tend to be linked to physical experience, language is characterised by abstract associations across networks of words. Research has suggested that language and simulation are compatible and complementary [@banksLinguisticDistributionalKnowledge2021; @kiela2014a; @louwerse2015a; @lam2015a; @pecherDoesPizzaPrime1998; @petilli2021a].

