

# Chapter 2 (Study 1): Investigating object orientation effects across 18 languages

\bigskip
\bigskip
\bigskip


```{r}

# This chapter is rendered by 'thesis-core.Rmd'. Thus, it inherits all the 
# parameters set in 'thesis-core.Rmd' and the objects loaded therein 
# (although no objects are used in this chapter).

```


\begin{adjustwidth}{1.5cm}{1.5cm}

At the beginning of my PhD, I contributed to a study led by Dr. Sau-Chin Chen (from Tzu Chi University, in Taiwan) and coordinated by the Psychological Science Accelerator (study page available at https://psysciacc.org/002-object-orientation). This study revisited the object orientation effect, which taps into sensorimotor simulation in conceptual processing. In addition the orientation congruency factor, this study incorporated two variables. The first variable was an individual difference measuring each participant's ability to mentally rotate objects. The second variable was the language of testing, with 18 languages being used. The object orientation effect was not replicated. Furthermore, the mental rotation and the language variables did not interact with the effect. In the present chapter, I describe this study and discuss several aspects regarding measurement error, replication and future crosslinguistic studies in conceptual processing.

\end{adjustwidth}

\bigskip
\bigskip
\bigskip


One of the seminal findings supporting the sensorimotor basis of conceptual processing was the object orientation effect. @stanfieldEffectImpliedOrientation2001 observed this effect in a sentence-picture verification task. On each trial of this task, participants first read a sentence such as ‘The eagle is in the nest’. On the next screen, they saw a certain picture and had to verify whether the protagonist of the sentence was present in the picture. Thus, following the previous example, if the picture showed an eagle, participants would click on the *yes* button. The key manipulation of this paradigm, unbeknownst to participants, was that the protagonist shown in the picture could either match or mismatch the orientation that had been implied in the sentence. For instance, following the example sentence above, if participants saw an eagled perched on a branch, the orientation would be matched. If, instead, the eagle were flying, the orientation would be mismatched. The theory of embodiment in language comprehension sustains that people mentally simulate perceptual and motor features of meaning [@barsalouPerceptualSymbolSystems1999a; @pulvermullerWordsBrainLanguage1999]. Therefore, according to Stanfield and Zwaan, pictures with a mismatching orientation (compared to pictures with a matching orientation) would incur processing costs, as participants would need to adjust their mental simulation of the scene. Indeed, Stanfield and Zwaan observed such an orientation match advantage in their results.

However, subsequent studies revisiting the object orientation effect revealed mixed results. The finding replicated more successfully in English than in other languages [@rommersObjectShapeOrientation2013; @kosterMentalSimulationObject2018; @chenDoesObjectSize2020; @zwaanRevisitingMentalSimulation2012; @dekoningMentalSimulationFour2017]. One of the non-replications received a response from @zwaanReplicationsShouldBe2014, who argued that the replication was underpowered---lacking a sufficient sample size---and pointed to several methodological differences with the original study. These comments are noteworthy, and will resonate throughout the present thesis. First, it should be seriously considered whether the sample sizes used in replications are sufficient. Recent research in neuroscience suggested that studying a certain question---namely, the mapping of individual differences at the structural and the functional levels---requires far more than the 25 participants that make up the average sample size in this topic. Rather, the necessary sample size is around 10,000 participants [@marekReproducibleBrainwideAssociation2022]. In our topic of interest, it is just possible that the necessary sample sizes far exceed the figures we are used to. A second, crucial issue to consider regarding replications is the fact that the results of our research are absolutely dependent on the method we use, as we demonstrate in Study 2 within the present thesis. From the operationalisation of the research question to the statistical analysis, every decision could have a great impact on the results [@barsalouEstablishingGeneralizableMechanisms2019]. For instance, @noahWhenBothOriginal2018 found that the facial-feedback effect was eliminated when participants were aware of being recorded. @barsalouEstablishingGeneralizableMechanisms2019 described the variables that can influence an experiment by alluding to the 'quantum perspective'. That is, a myriad variables can affect the expression of the cognitive mechanism by which a cognitive effect arises. Furthermore, the manifestation of the effect in the experimental situation (traditionally, in the laboratory) need not be the genuine manifestation of the effect. On the contrary, the experimental setting tends to be far removed from the real-life settings of our processes of interest. Against this backdrop, it is not surprising that effects sometimes do not replicate. I do not think this realisation should lead us to a nihilistic or a fatalistic standpoint, where we give up our hopes of reaching any trustworthy conclusions. On the contrary, as Barsalou contends, we could approach the quantum perspective by scrutinising the variability that underlies the cognitive/experimental effects we study [see @cummingNewStatisticsWhy2014].^[Thank you to Dr. Margriet Groen and Prof. Max Louwerse for a discussion on this topic.]


# Study and methods

@chenInvestigatingObjectOrientation2018 revisited the object orientation effect by conducting a large, crosslinguistic study (for materials and updates on this study, please see https://osf.io/e428p).^[Please note that the preprint of @chenInvestigatingObjectOrientation2018 mentions '14' languages but finally 18 languages were present in the study.] The design comprised the classic sentence-picture verification task, with objects matching or mismatching the orientation implied in the preceding sentence on each trial. The sample size was far larger than the average in the field. English had 1,363 participants. The other languages had a minimum of 50 and a maximum of 262 participants. This large sample size was necessary to cater to the possibility of a non-replication, which would undoubtedly raise the caveat that the sample size was insufficient. Furthermore, the study also included an individual difference that measured participants’ ability to mentally rotate objects. The inclusion of such an individual difference in the model was motivated by previous suggestions that this ability could act as a confound, by interfering with the effect of interest [@chenInvestigatingObjectOrientation2018]. Such a possibility was not too remote, according to recent research that has highlighted the role of participant-specific cognitive biases [@delucaRedefiningBilingualismSpectrum2019; @montero-melisConsistencyMotionEvent2021].

The results were analysed using mixed-effects models. The specific approach adopted with these models was not very conservative, as random slopes were not included in the model due to their lack of significance. This contrasts with the approach we took in Study 2, by which we pursued a maximal random-effects structure to create a conservative analysis [@brauer2018a; @singmann2019a].


# Results

The results did not present a main effect of orientation match in any of the 18 languages. Furthermore, the mental rotation score was not found to predict the (non-significant) difference between the match and the mismatch conditions. 


# Discussion

Taken together, and considered in light of previous non-replications, the present study supports the absence of the object orientation effect, even though---arguably---the jury always remains out in psychological science. In my view, both original results and replications are subject to questioning, and it is only through the accumulation of consistent findings that we can increase our certainty. When non-replications accumulate and we our certainty about an effect declines, it is time to consider why a theory is supported by certain operationalisations and only weakly supported (if at all) by other operationalisations. Examining the role of the operationalisation is a key step in the replication cycle, and I think this question will require more research over the coming decades. In the present thesis, we can compare two operationalisations of the embodied cognition theory. In Study 1, the object orientation effect has been used, which implements a factorial design. That is, the main independent variable is made up of categorical levels. Interestingly, the action-sentence compatibility effect---which could not be replicated recently [@moreyPreregisteredMultilabNonreplication2022]---also involves a factorial design. In contrast, in Study 2, we will use continuous variables capturing the degree of visual information associated with words (among other variables). Thus, one of the questions that should be examined in future research is whether the nature of the independent variables---e.g., categorical versus continuous---could account for the replication success. Insofar as continuous variables contain more information than categorical ones, the former type might offer more statistical power [@cohenCostDichotomization1983; @petilli2021a].

Furthermore, the study of @chenInvestigatingObjectOrientation2018 was pioneering as it investigated the object orientation effect across 18 languages, including Arabic, Hebrew, Polish, Simplified Chinese and Turkish. The breadth of crosslinguistic variation deployed in this study constitutes a very novel contribution to the topic of conceptual processing. Precisely the scarcity of precedents makes such a crosslinguistic investigation challenging nowadays. Thus, we could now consider some desirable characteristics for future studies, such as the need to reach sufficient sample sizes in all languages. Determining a sufficient sample size will require a conservative power analysis that should itself be based on a sufficient amount of reliable data [@albersWhenPowerAnalyses2018]. Furthermore, to prevent the misinterpretation of crosslinguistic differences, all languages should have the same sample size. 

Last, for the longer term, it would be desirable to work towards a theory of crosslinguistic variation in conceptual processing, which would help in the design of studies and in the interpretation of any crosslinguistic differences. This goal will require research on the lexicosemantic and syntactic differences across languages that are relevant to the effect of interest in conceptual processing (in this case, the object orientation effect). In @chenInvestigatingObjectOrientation2018, we outlined some typological differences across some of the languages examined; specifically, differences in the lexical encoding of motion [@verkerkCorrelationMotionEvent2014] and in the encoding of placement [@newmanCrosslinguisticOverviewPosture2002]. While this was hopefully a move in the right direction, I think that future empirical work with a crosslinguistic aspiration would necessitate further typological theory. This is very much uncharted territory in the topic of conceptual processing, so it is exciting but also uncertain. To help chart the course, the topic area of linguistic relativity is likely to contain useful resources and examples. For instance, @bernabeuMoreRefinedTypology2019 suggested that a novel typological classification of motion [@verkerkCorrelationMotionEvent2014] could be useful for the design of studies in linguistic relativity. Specifically, @verkerkCorrelationMotionEvent2014 created a numeric rating for the degree to which 20 Indo-European languages adhered to the pattern of satellite-framing and verb-framing. This represented a major step beyond the dichotomic division between the two satellite and verb framing. Indeed, Verkerk put numbers to the nuances holding across 20 languages. Bernabeu and Tillman suggested the use of Verkerk's classification in the organisation of linguistic relativity studies. Arguably, the kind of theoretical and methodological instruments that are available for investigating lingusitic relativity will also be necessary for the crosslinguistic study of conceptual processing. In conclusion, incorporating a crosslinguistic strand to the study of conceptual processing might lead us to realising the role of language-specific patterns, now that we have realised the role of the semantic context and of participants' individual differences (both aspects addressed in the next chapter). 

Three of the topics discussed in this chapter constitute key elements of the next chapter, which will describe Study 2. The first of these topics is the role of sensorimotor simulation in conceptual processing. The second topic is the role of individual differences. The third topic is the importance of statistical power. In addition to these topics, Study 2 will also incorporate the language system to the study of conceptual processing. Whereas sensorimotor simulation is characterised by detailed representations that tend to be linked to physical experience, language is characterised by abstract associations across networks of words. Research has suggested that language and simulation are compatible and complementary [@banksLinguisticDistributionalKnowledge2021; @kiela2014a; @louwerse2015a; @lam2015a; @pecherDoesPizzaPrime1998; @petilli2021a].

