

# Chapter 1: Introduction


```{r}

# This chapter is rendered by 'thesis-core.Rmd'. Thus, it inherits all the 
# parameters set in 'thesis-core.Rmd' and the objects loaded therein 
# (although no objects are used in this chapter).

```


The process by which people understand the meaning of words is known as conceptual (or semantic) processing. The scientific study of this ability since the 1960s was first characterised by categorical taxonomies. That is, concepts were described using lists of features containing some properties that were deemed necessary and other properties deemed sufficient [@fillmore1975alternative]. For instance, necessary features of a dog might include having a tail, paws, barking, etc. In turn, being identified as a dog was a sufficient condition for being a mammal. Although useful, this 'checklist' approach was not devoid of shortcomings. For instance, a dog in real life can actually lack any of the aforementioned 'necessary' conditions. Furthermore, some of the necessary features are more paradigmatic than others for a given category. For instance, barking is more paradigmatic of a dog than having ears. In addition, the some sufficient conditions are more paradigmatic than others. For instance, a dog is more paradigmatic of the mammal category than a platypus. These shortcomings were addressed by the Prototype Theory, which posited that concepts were organised around core concepts, or *prototypes*. Thus, the Prototype Theory accounted for the prototypical position of barking among the necessary features of dogs, and for the less prominent position of ears among the same features. Similarly, Prototype Theory helped explain the prototypical position of dogs in the category of mammals [@roschCognitiveRepresentationsSemantic1975]. Furthermore, the nuanced category membership offered by Prototype Theory aptly accounted for subtle differences among abstract concepts. For instance, @colemanPrototypeSemanticsEnglish1981 delved into the concept of *lie*, which has many variants and can only be properly considered in light of the context. For instance, a white lie intended to spare suffering may not always be classified as a lie. 

A different group of cognitive psychologists approached conceptual processing differently, contending that the complex hierarchies associated with Prototype Theory might be unnecessary. Instead, @collinsSpreadingactivationTheorySemantic1975 argued that the language system encoded in people's minds provides access to the meaning of concepts by means of abstract, symbolic relationships, or *Spreading Activation* [@loftusSpreadingActivationSemantic1975]. This claim was in turn regarded by the proponents of Prototype Theory as a post-hoc explanation lacking precision [@roschReplyLoftus1975].

Around two decades later, the field of embodied cognition emerged, organised around the tenet of neural reuse [@barsalouPerceptualSymbolSystems1999; @pulvermullerWordsBrainLanguage1999; @barsalouSituatedSimulationHuman2003]. Specifically, proponents of embodied cognition in conceptual processing contended that the brain regions in charge of perception and action contributed to the understanding of words by providing simulations, or reenactments [@andersonNeuralReuseFundamental2010; @barsalouStayingGroundedAvoiding2016]. In this way, brain regions were reused during conceptual processing, a mechanism that would be spatially efficient. 


## Language and embodiment

Hereafter, we will delve into the more recent research introduced above. Two strands stand out: language and embodiment. Research over the past two decades has suggested that conceptual processing involves both 'linguistic' and 'embodied' systems of the brain. First, the language system is characterised by associations across networks of words [@landauerIntroductionLatentSemantic1998; @pylyshynWhatMindEye1973]. For instance, the word 'window' often co-occurs with 'door', whereas 'window' seldom co-occurs with 'sheep'.^[The reader is encouraged to consult the relationship between these and other words using the Latent Semantic Analysis website at http://lsa.colorado.edu, where they can select the option 'Matrix Comparison'.] Second, the embodiment system is characterised by associations within perceptual, motor, affective and social domains [@barsalouPerceptualSymbolSystems1999; @diveicaQuantifyingSocialSemantics2022]. For instance, reading the words 'green' or 'red' can activate the same areas that activate upon seeing those colours [@simmonsCommonNeuralSubstrate2007]. Both language and embodiment have strengths and limitations [@bernabeuModalitySwitchesOccur2017; @connell2019a; @dove2020a; @kumar2021a; @louwerse2015a; @mahon2016a], which we address below. For example, several avenues of research support the idea that linguistic information may be activated more quickly, and reach peak activation before embodied information [@louwerseTasteWordsLinguistic2011; @santosPropertyGenerationReflects2011; @simmonsFMRIEvidenceWord2008], but this mechanism may be dependent on contextual factors such as semantic depth [@connellPrinciplesRepresentationWhy2014; @petilli2021a]. As a result, conceptual processing flexibly draws on these systems following the demands of the context [@satoTaskRelatedModulation2008; @shebaniFlexibilityLanguageAction2018; @willemsFlexibilityEmbodiedLanguage2011]. Furthermore, research in computational linguistics has further supported the complementarity of language and embodied information, by revealing increased predictive performance when models are provided with perceptual information on top of text-based information [@NIPS2013_7cce53cf; @roadsLearningUnsupervisedAlignment2020].

The terminology used in this topic deserves a note. The first terms of note are language and embodiment. These terms provide the building blocks for the study of a more involved phenomenon, as with other dichotomies used in psychology [e.g., @kahnemanThinkingFastSlow2011; @paivioMentalRepresentationsDual1990]. Particularly noteworthy is the term 'embodiment', which encompasses sensory, motor, affective and social information [@borghiWordsSocialTools2019; @newcombeEffectsEmotionalSensorimotor2012; @zwaanTwoChallengesEmbodied2021]. These systems have helped organise the study of conceptual processing over the past decades. First, language refers to a system of word-to-word associations that are not operationalised in a modality-specific way. These associations are amodal in that they are operationalised using text-based networks of words [@andrewsReconcilingEmbodiedDistributional2014; @louwerse2015a]. The language system can be operationalised as a variable using word co-occurrence, which is a calculation of the high-order distance between words [@petilli2021a; @wingfieldUnderstandingRoleLinguistic2022]. The term 'high-order' designates relationships across networks of words, as opposed to direct relationships [@landauerIntroductionLatentSemantic1998]. On the other side of the coin, the embodiment system is modality-specific in that it grounds the meaning of words in thematically-relevant areas of the brain. The activation of these areas during semantic processing creates a simulation that contributes to the comprehension of concepts [@barsalouPerceptualSymbolSystems1999]. The embodiment system agglutinates four major systems: perception [@connell2019a], action [@vukovicPrimaryMotorCortex2017], emotion [@kousta2011a] and sociality [@wangSocialEmotionDimensional2021]. Furthermore, the perceptual domain in turn comprises vision, hearing, touch, etc. Although these general levels are worth noting due to the influence over the past decades, it is essential in specific studies to define the object of study more precisely [@zwaanTwoChallengesEmbodied2021], which we think is the general norm. Last, we should note that we will often use the terms 'language-based' and 'vision-based' in this thesis. These terms are practically equivalent to 'linguistic' and 'visual', respectively. However, the latter terms are loaded with associations to languages, on the one hand, and to direct visual perception, on the other hand. Because those associations differ from our intended meaning, we will often use 'language-based' and 'vision-based', as did @petilli2021a.

The language system is involved in the representation of both abstract and concrete concepts [@ponari2018a; @regginDevelopmentAbstractWord2021]. For instance, measures of distributional semantic distance---solely based on texts from large corpora---have been shown to capture aspects of the real world with considerable accuracy [@contreraskallensQuantifyingInterdisciplinarityCognitive2022; @dedeyneBetterExplanationsLexical2013; @kumarDistantConnectivityMultiplestep2020; @louwerseLanguageEncodesGeographical2009]. The language system is likely more important for the processing of abstract---rather than concrete---concepts, as abstract concepts tend to have reduced sensorimotor content [@barca2020a; @dunabeitiaQualitativeDifferencesRepresentation2009; @hultenNeuralRepresentationAbstract2021], although the degree of this difference could be small [@dedeyneBetterExplanationsLexical2013]. Language-based regularities may even allow distinguishing between concrete and abstract words, as word concreteness is consistently related to linguistic characteristics such as part of speech, morphological structure, countability and etymology [@lieversLinguisticDimensionsConcrete2021]. 

Regarding the time course, the language system is activated more quickly in semantically-deep tasks [@connell2013a; @louwerseTasteWordsLinguistic2011], whereas both systems are similarly fast in semantically-shallow tasks [@petilli2021a]. For instance, @louwerseTasteWordsLinguistic2011 found that language-based information better predicted rapid responses, while perceptual information better predicted slower responses. In turn, responses of intermediate duration were equally well predicted by both types of information. As a result of these characteristics, the language system is equipped to support a major part of conceptual processing [@connell2019a; @connellSeeHearWhat2014]. However, the language system is hindered by the symbol grounding problem, which refers to the impossibility of obtaining meaning---or 'grounding' lexical content in reality---on the sole basis of language-based associations [@guntherLimitsAutomaticSensorimotor2021; @guntherSymbolGroundingDirect2018; @louwerseSymbolInterdependencySymbolic2011; @harnadSymbolGroundingProblem1990]. That is, having only word-to-word associations leads to a circularity where *meaning* is never associated with anything in the real world. This is why embodied simulation is deemed useful. Another limitation is caused by the finite vocabularies of languages, which sometimes fall short of the richness of sensorimotor experience [@guntherLimitsAutomaticSensorimotor2021; @dedeyneVisualAffectiveMultimodal2021; @majidOdorsAreExpressible2014; @majidSensesLanguageCulture2011; @majidCanNomenclatureBody2015]. Consider all the sensory, motor, affective and social experiences that cannot be described with a word in your language. Taken together, the great importance of the language system across studies and across contexts suggests  that language-based associations are necessary for conceptual processing. In addition, modality-specific information seems to play a significant---if smaller---role, and is especially relevant in contexts of deeper semantic processing. If this is indeed the case, we could hypothesise that language is necessary but not sufficient, insofar as some contexts present a significant contribution of modality-specific information.

The embodiment system is best suited for the representation of concrete concepts, such as those involving perceptual features [@pecherDoesPizzaPrime1998; @yeeColorlessGreenIdeas2012; @ostarekTaskdependentCausalRole2017] and actions [@riccardiDissociatingActionAbstract2019], such as *table* or *hammer*. Some research has suggested that embodied simulation plays an integral role in conceptual processing [@pulvermullerHowNeuronsMake2013], at least in the context of relatively deep semantic tasks---e.g., classifying abstract and concrete words---and relatively concrete concepts---e.g., *table* [@leboisAreAutomaticConceptual2015; @pecherDoesPizzaPrime1998; @yeeColorlessGreenIdeas2012; @ostarekTaskdependentCausalRole2017; @connellWeKnowWhat2016; @garciaTimeFaceLanguage2020; @shebaniWhatImpairedSpatial2021; @vitaleNeuralInhibitionNetwork2021; @vukovicPrimaryMotorCortex2017; @wangSocialEmotionDimensional2021]. Further evidence for the contextual dependency of the interplay between language and sensorimotor information was found by @riccardiDissociatingActionAbstract2019, who investigated the comprehension of action verbs and abstract verbs in left-hemisphere stroke patients, finding that the processing of action concepts relied more heavily on sensory-motor areas. Furthermore, studies have suggested that even abstract concepts may be partially grounded in modality-specific domains such as emotion, sociality and interoception [@concaSearchDifferentCategories2021; @connellInteroceptionForgottenModality2018; @diveicaQuantifyingSocialSemantics2022; @kousta2011a; @vigliocco2014a; @wangSocialEmotionDimensional2021; @borghiAbstractConceptsExternal2022]. For example, the relatively-abstract concepts of *fear* and *sadness* are rated as being highly interoceptive [@connellInteroceptionForgottenModality2018].

However, other research has curtailed the importance of the embodiment system [@mahonCriticalLookEmbodied2008; @bottiniConcretenessAdvantageLexical2021; @garceaPreservedToolKnowledge2013; @guntherSymbolGroundingDirect2018; @guntherLimitsAutomaticSensorimotor2021; @montero-melisNoEvidenceEmbodiment2022; @vannuscorpsPersistentSparingAction2016]. For instance, studies have found that lesions to motor brain areas did not systematically impair the processing of action concepts in language [@papeoActionPerformanceActionword2010; @negriWhatRoleMotor2007]. Furthermore, behavioural studies from the past decade have begun constraining the role of perceptual simulation. For instance, @louwerseTasteWordsLinguistic2011 found that perceptual simulation was more important late in the time course of property verification [also see @bernabeu2017a]. In another study, @connellSeeHearWhat2014 found that the auditory information in words is relevant for reading aloud but not so much for word identification. Importantly, even the keenest critiques of embodiment have not  denied that conceptual processing can involve activation of sensory and motor systems. What they questioned was the role of these activations. For instance, @mahonCriticalLookEmbodied2008 argued that these activations could be a by-product of comprehension rather than a contributor to comprehension. In conclusion, the language and the embodiment systems are complementary to each other [@andrewsIntegratingExperientialDistributional2009; @dedeyneVisualAffectiveMultimodal2021; @wangNeuralRepresentationAbstract2010]. 

The division between language and embodiment has provided fruitful avenues for research and yielded a prolific output over the past two decades [@connell2019a], and many more research avenues are yet to be explored [@bernabeu2021a].^[The pregistration in @bernabeu2021a had to be sidelined due to project adjustments required during the Covid-19 pandemic. We hope that the research questions laid out in this preregistration inspire future research.] However, with more than two decades of history, it may be pertinent to appraise this division and consider alternatives. First, we know that the categories we have in our research toolkit may be a bit arbitrary [@tulvingAreThere2562007]. Second, cognitive science research needs to be open to change. In a recent discussion, @michelOvercomingModalAmodal2021 contended that there is a stalemate between the amodal and the modal views. On the one hand, the amodal view has an 'ad-hoc air'. This criticism echoes the adjective of 'post-hoc' that had been used by @roschReplyLoftus1975 in relation to the spreading activation stance. On the other hand, the modality-specificity---or embodiment---stance is challenged by having smaller effect sizes [@louwerse2015a] and by some non-replications [@moreyPreregisteredMultilabNonreplication2022; @wagenmakersRegisteredReplicationReport2016]. The smaller effect sizes and the non-replications may be more closely related than we often acknowledge, as some effects can require sample sizes far exceeding what we are used to [@marekReproducibleBrainwideAssociation2022], and non-replications require the consideration of alternative explanations [@noahWhenBothOriginal2018]. Regarding sample size, where very large sample sizes are necessary to study some effects, the onus will be on scientists to decide whether we can and should invest the required funding.

In sum, @michelOvercomingModalAmodal2021 proposed working towards a continuous construal of language and embodiment in conceptual processing.  I am sympathetic to this view, as continuums---that is, the use of gradual, continuous measures---often outperform categorical divisions in science. For instance, consider the move from categorical factors to continuous variables in the area of conceptual processing [@lynottModalityExclusivityNorms2009; @petilli2021a]. Part of the reason for the advantage of continuous measures probably lies in the fact that they involve more data, thus offering greater precision. At the same time, however, taking the leap advocated by Michel will require reframing a longstanding discussion. I look forward to following such a development in the future. In the present work, I have adhered to the language-embodiment division, although my use of continuous predictors aligns with the goal of a continuum between language and embodiment. In this way, I have investigated how the interplay between language and sensorimotor simulation is reflected at various levels of the experimental structure---namely, at the levels of individuals, words and tasks. In closing, if/when the field attempts to overcome the opposition between language and embodiment, I think it will be important to consider such a move in the context of neuroscience, too. That is, is it neuroscientifically plausible to conceive of a single system? Research has demonstrated the role of amodal regions of the brain and of modality-specific regions during conceptual processing, showing signs of a continuous progression in spite of the separate specialisation of the areas [@binderNeurobiologySemanticMemory2011; @fernandinoConceptRepresentationReflects2016]. In a recent study, @kuhnkeTaskdependentFunctionalEffective2021 observed a functional coupling---that is, a functionally useful interplay---between amodal and modal areas, characterised by a flow of information in both directions. Arguably, this research provides some support for Michel's continuum proposal.

One of the core reasons why it is important to investigate language and embodiment is the optimality of scientific theories, classically epitomised by Occam's razor. Occam's razor represents the desirability of concise theories. Put concretely: if one single mechanism could explain a cognitive process, only one mechanism should be used. @galleseBrainConceptsRole2005 were among the first to articulate the Occam's razor argument within the present topic. The authors argued: 'In short, we think there is an Occam’s Razor argument here. The modality-neutral structure is just not needed.' (p. 468). Gallese and Lakoff wrote that in 2005. Importantly, since then, a sizable amount of evidence has challenged the role of embodiment by suggesting that sensorimotor activations are not conducive to meaning, but are instead of a result of comprehension [@hickokMythMirrorNeurons2014; @mahon2016a; @mahonCriticalLookEmbodied2008], and other evidence has favoured the 'hybrid' theory, as reviewed above. Indeed, as reviewed above, research has extensively investigated how language and embodiment interact as a function of the concreteness of concepts and the semantic depth required by the context. In contrast, the role of individual differences has received less attention. Furthermore, most of these studies have investigated how individual differences interact with either language or sensorimotor simulation. For instance, @pexman2018a found that higher-vocabulary individuals were more sensitive to task-relevant information, such as word concreteness, when performing a task that required classifying words as abstract or concrete. Similarly, research has found that physical expertise and perceptual biases are associated with differences in the mental simulation of meaning [@beilockSportsExperienceChanges2008; @calvo-merinoActionObservationAcquired2005; @vukovic2015a]. In spite of the advancements, there is room for the investigation of further combinations, such as the way in which vocabulary knowledge interacts with both language-based information and vision-based information.


## The present thesis

Chapter 2 describes Study 1, a multi-lab study from the Psychological Science Accelerator to which I contributed. This study revisited the object orientation effect [@chenInvestigatingObjectOrientation2018], which taps into sensorimotor simulation in conceptual processing. As I review in Chapter 2, replicating the object orientation effect is important due to its seminal influence and to the existence of mixed findings. Thanks to a worldwide network of laboratories, this study boasted a sample of over 3,000 participants. Furthermore, the study examined the role of individual differences in mental rotation as well as the role of language of testing. I contributed theoretical and methodological suggestions to this study from an early stage, recorded a demonstration video (https://osf.io/h36wr), contributed data collected from 50 participants at Lancaster University, and then contributed to the reporting. From now, I look forward to contributing to the latest revisions of this Stage II Registered Report, before the submission to Psychonomic Bulletin & Review, where this registered report was accepted in principle. 

Study 1 did not replicate the object orientation effect. Furthermore, it revealed that neither mental rotation nor language interacted with the effect. Since the statistical power reached in this study is larger than that of most previous studies addressing the object orientation effect, it is especially important to reflect on the non-replication. It will be especially important to investigate the methodological characteristics that influence the robustness of effects. That is, in addition to the real effect size of each effect (which can only be estimated in research), and in addition to the statistical power of studies (which is highly dependent on the sample size), what does the operationalisation bear on the results? One possible influence is the categorical or continuous nature of independent variables. 

Chapter 3 describes Study 2, which is formed of three studies (2.1, 2.2 and 2.3). These studies are thus grouped because they address the same overarching question [see @wingfieldUnderstandingRoleLinguistic2022 for a similar format]. This question is how the interplay between language and sensorimotor information manifests itself at the levels of individuals, words and tasks. Furthermore, the study addresses the importance of sample size by estimating how many participants would be necessary to reliably detect several effects of interest. Whereas in Study 1 the task used was specific to sensorimotor simulation, the tasks used in Study 2 are semantic priming, semantic decision and lexical decision, which allow the analysis of both language-based and vision-based information. It was important for us to incorporate language because research has suggested that language is complementary to sensorimotor information, and that it has a greater influence than the latter. At the level of individual differences, Study 2 examined vocabulary size and included general cognition covariates which are important to control for. In addition, the influence of participants' gender was considered, as some research has suggested that language-based information could be more influential in females than in males. At the word level, text-based variables were used as indices of language-based information, whereas vision-based variables indexed sensorimotor information. As covariates, lexical information and word concreteness were included in the analyses. The covariates were included to attain a higher degree of certainty regarding the effects of interest, as the former and the latter were often correlated. Furthermore, these analyses included random effects, which were important to preserve the assumption of independence of observations, due to the presence of repeated measures. 

The results revealed a prominent influence of language-based information and a smaller effect of vision-based information. Furthermore, the results revealed a set of interactions suggestive of a 'relevance advantage' in higher-vocabulary participants. That is, these participants were more sensitive to task-relevant features of the words, such as language-based information in lexical decision and  word concreteness in semantic decision. Last, statistical power analyses revealed the need to dramatically increase sample sizes for studying vision-based information, as well as for studying the interaction of both language-based and vision-based information with vocabulary size, gender and presentation speed.



