

# General discussion of the thesis

This thesis has investigated how the interplay between linguistic and sensorimotor systems in conceptual processing manifests at the levels of individuals, tasks and stimuli. Furthermore, we have inquired what sample sizes are required to reliably investigate a range of questions in conceptual processing. 

## Key findings

The work of this thesis has provided several novel findings and theoretical contributions, extending the body of knowledge in the domains of conceptual processing and embodied cognition. 

First, Chapter 1 addressed the study of @chenInvestigatingObjectOrientation2018a, to which I have contributed. This study revisited the object orientation effect, which has been influential in the study of sensorimotor simulation. The design comprised the classic sentence-picture verification task, with objects matching or mismatching the orientation implied in the preceding sentence on each trial. Furthermore, the study tracked the effect across 18 languages, and in Chapter 1, I offered some suggestions for future crosslinguistic studies in conceptual processing. The study also included an individual difference measuring participants’ ability to mentally rotate objects, as previous research had suggested that this ability could act as a confound. The results did not present a main effect of orientation match, nor an interaction between the latter and language or mental rotation. In conclusion, the most general summary is that the object orientation effect was not replicated. Future studies would benefit from the availability of power analyses to estimate adequate sample sizes, from a language typology background to guide crosslinguistic comparisons, and from the balancing of sample sizes across all languages examined in a study to allow the interpretation of any crosslinguistic differences. 

Second, the present thesis has suggested that both language-based information and perceptual simulation contribute to the comprehension of words, consistent with a hybrid theory of conceptual processing centred on the interplay between language and embodiment [@barsalouLanguageSimulationConceptual2008; @louwerseSymbolInterdependencySymbolic2011; @connellSeeHearWhat2014]. In Studies 2.1, 2.2 and 2.3, we delved into the effects of language-based and vision-based information at the levels of individuals, words and tasks. Both language and vision played significant roles in some contexts (detailed below), even when important covariates such as word concreteness and individual differences in general cognition had been controlled for, and when the models had a maximal random-effects structure providing for a conservative analysis. Importantly, language was more influential than vision overall. 

Third, a 'task-relevance advantage' was identified in higher-vocabulary participants. Specifically, in lexical decision, higher-vocabulary participants were more sensitive than lower-vocabulary participants to language-based information. In contrast, in semantic decision, higher-vocabulary participants were more sensitive to word concreteness. Crucially, to isolate the confounding influence of general cognitive abilities different from vocabulary, the analyses in Studies 2.1 (semantic priming) and 2.2 (semantic decision) included general cognition covariates---i.e., attentional control and information uptake. In summary, the present findings suggest that greater linguistic experience may be associated with greater task adaptabiity during cognitive performance, with better comprehenders able to selectively attend to task-relevant features compared to poorer comprehenders [@lim2020a; @pexman2018a].

Fourth, the semantic priming paradigm analysed in Study 2.1 revealed that both language and vision were more important with the short SOA (200 ms) than with the long SOA (1,200 ms). This finding replicates some of the previous literature [@petilli2021a] while highlighting the importance of the time course and the level of semantic processing. That is, although the finding seems to be at odds with the theory that perceptual simulation peaks after language-based associations [@barsalouLanguageSimulationConceptual2008; @louwerseTasteWordsLinguistic2011], the long SOA may have been too long for perceptual simulation to be maintained in the lexical decision task that was performed by participants, which is semantically shallow [@petilli2021a]. A follow-up on this issue is outlined in ‘Future directions’ below.

Fifth, a human-based measure of visual information, created using ratings [@lynott2020a] was found to be superior to a computational measure created using neural networks [@petilli2021a]. This finding is consistent with a body of literature suggesting human-based measures are superior to computational measures [@de2016a; @de2019a; @gagneProcessingEnglishCompounds2016; @schmidtke2018a; cf. @michaelovClozeFarN4002022; @snefjella2020a]. Furthermore, the difference between the results of the variables resonates with the finding that simpler variables sometimes outperform more complex variables [@wingfieldUnderstandingRoleLinguistic2022]. Last, future experimental or theoretical work could investigate whether the use of human-based measures to predict human behaviour poses a major problem of circularity that could (in part) invalidate the conclusions of such research [@petilli2021a].

Sixth, we discussed the confounding role of measurement instruments, in relation to the comparison described above between the human-based and the computational variable. ‘Accidents of history’ in a research field---that is, events lacking a rational causation---may influence important research conclusions. Consider the situation of a field in which some work has been devoted to improving the precision of certain variables over years. This has been the case in computational psycholinguistics, with the creation of text-based variables such as Latent Semantic Analysis, Hyperspace Analog to Language and ‘word2vec’ [@jones2006a; @lund1996a; @mandera2017a; @mikolovEfficientEstimationWord2013; @dedeyneBetterExplanationsLexical2013; @de2016a; @guenther2016a; @guntherLatentSemanticAnalysis2016; @wingfieldUnderstandingRoleLinguistic2022]. All else being equal, a competition between one of the research-based supervariables and any non-engineered variable would have a likely winner---the supervariable. Nowadays, in conceptual processing, it is necessary to compare the role of text-based semantic variables, such as the aforementioned ones, to embodiment variables measuring the perceptual, motor, emotional or social information in words. Whereas text-based variables boast a history of steady incremental improvement over time, embodiment variables are more recent and have not undergone such a process. While we do not think that this accident of history fully explains the superiority of language-based information in the present analyses and in many previous analyses, we think it would be valuable to continue reflecting on the confounding role of measurement instruments, and indeed to consider whether some engineering work---as it were---should be applied to embodiment variables too.

Seventh, we delved into the issue of statistical power, and reviewed recent findings suggesting that the sample size required for adequate analyses in topics of cognitive psychology and neuroscience far exceed the sample sizes we are used to. Furthermore, we calculated the sample size required to reliably approach several effects of interest in conceptual processing. For this purpose, we performed Monte Carlo simulations using the models from our main analyses. The results suggested that 300 participants were sufficient to examine the effect of language-based information contained in words, whereas more than 1,000 participants were necessary for the effect of vision-based information and for the interactions of both former variables with vocabulary size, gender and presentation speed (i.e., SOA). These analyses of sample size requirements have ramifications for future research in conceptual processing. While the general pattern is that sample sizes should be increased, the findings also highlight how important it is to consider the specific main effects or interactions that are of greatest theoretical importance. For example, while it would likely take thousands of participants to examine the interaction between gender and language or vision, a much smaller sample would suffice to examine the interaction between vocabulary size and language or vision. 


## Future directions

We are currently preparing a study that will follow up on Study 2.1 by incorporating several enhancements. First, the study will incorporate a measure of participants’ visual ability as an effect of interest. Alongside this measure, there will be reading ability as another effect of interest and working memory as a covariate. At the word level, the effects of interest will be the same as those of Study 2.1---namely, language-based similarity and vision-based difference. This measure will be alongside one of reading ability    and will encompass several improvements.  an additional encompass the three main variables of interest from Study 2.1, namely, language and vision at the word level and language at the participant level.  along with  incorporate visual ability as an individual difference.  Thus, compare the effects of language and vision both at the level of   an individual difference variable measuring visual ability. In a recent study, @murakiSimulatingSemanticsAre2021 investigated how individual differences in motor imagery predicted motor simulation. In contrast to Muraki et al.’s study, the study we are preparing will measure individual differences in vision. Furthermore, at the word level, whereas Muraki et al. focussed on motor semantic features, our next study will encompass language-based and vision-based information. Indeed, our study will comprise language and vision at the levels of participants and words. 

Furthermore, our next study will address the time courses of language-based and vision-based processing. In Study 2.1, language and vision were both more important with the short SOA than with the long SOA. To address this comparison more reliably in our next study, we will implement a semantic priming paradigm with a semantic decision task, which elicits a deeper semantic processing than lexical decision, and is thus better suited for capturing the time course of linguistic processing and that of perceptual simulation [see @petilli2021a]. The concrete implementation of this task will be as follows. Participants will see a prime word and a target word on each trial, and they will assess whether the target word is abstract or concrete. Semantic decision also has the practical advantage that it involves fewer invalid trials than lexical decision, as semantic decision does not require any pseudowords. 

In addition, we will implement a recent recommendation from @petilli2021a to operationalise SOA as a continuous variable, rather than the typical categorical form. The continuous SOA measure will enable a more precise insight on the time course of language-based and vision-based information (for current materials and forthcoming updates on this study, see https://osf.io/gwh7x).

