

# Introduction

Research over the past two decades has suggested that conceptual processing involves both 'linguistic' and 'embodied' systems of the brain. The language system is characterised by associations across networks of words [@landauerIntroductionLatentSemantic1998; @pylyshynWhatMindEye1973], whereas the embodiment system is characterised by associations within perceptual, motor, affective and social domains [@barsalouPerceptualSymbolSystems1999; @diveicaQuantifyingSocialSemantics2022]. Both systems have strengths and limitations [@connell2019a; @dove2020a; @kumar2021a; @louwerse2015a; @mahon2016a]. As a result, conceptual processing flexibly draws on these systems following the demands of the context [@satoTaskRelatedModulation2008; @shebaniFlexibilityLanguageAction2018; @willemsFlexibilityEmbodiedLanguage2011].

The language system is involved in the representation of both abstract and concrete concepts [@ponari2018a; @regginDevelopmentAbstractWord2021]. For instance, measures of distributional semantic distance---solely based on texts---have been shown to capture aspects of the real world with considerable accuracy [@contreraskallensQuantifyingInterdisciplinarityCognitive2022; @dedeyneBetterExplanationsLexical2013; @kumarDistantConnectivityMultiplestep2020; @louwerseLanguageEncodesGeographical2009]. Although the language system is likely more important for the processing of abstract---rather than concrete---concepts [@barca2020a; @dunabeitiaQualitativeDifferencesRepresentation2009; @hultenNeuralRepresentationAbstract2021], although the degree of this difference could be small [@dedeyneBetterExplanationsLexical2013]. Language-based regularities may even allow distinguishing between concrete and abstract words, as word concreteness is consistently related to linguistic characteristics such as part of speech, morphological structure, countability and etymology [@lieversLinguisticDimensionsConcrete2021]. 

Regarding the time course, the language system is activated more quickly in semantically-deep tasks [@connell2013a; @louwerseTasteWordsLinguistic2011], whereas both systems are similarly fast in semantically-shallow tasks [@petilli2021a]. As a result of these characteristics, the language system is equipped to support a major part of conceptual processing [@connell2019a; @connellSeeHearWhat2014]. However, the language system is hindered by the symbol grounding problem, which refers to the impossibility of obtaining meaning---or 'grounding' lexical content in reality---on the sole basis of word-to-word associations [@guntherLimitsAutomaticSensorimotor2021; @guntherSymbolGroundingDirect2018; @louwerseSymbolInterdependencySymbolic2011; @harnadSymbolGroundingProblem1990]. Another limitation is caused by the finite vocabularies of languages, which sometimes fall short of the richness of sensorimotor experience [@guntherLimitsAutomaticSensorimotor2021; @dedeyneVisualAffectiveMultimodal2021; @majidOdorsAreExpressible2014; @majidSensesLanguageCulture2011; @majidCanNomenclatureBody2015]. In conclusion, word-to-word associations appear to be necessary but not sufficient for conceptual processing.

The embodiment system is best suited for the representation of concrete concepts, such as those involving perceptual features [@pecherDoesPizzaPrime1998; @yeeColorlessGreenIdeas2012; @ostarekTaskdependentCausalRole2017] and actions [@riccardiDissociatingActionAbstract2019]. Some research has suggested that embodied simulation plays an integral role in conceptual processing [@pulvermullerHowNeuronsMake2013], at least in the context of relatively deep semantic tasks and relatively concrete stimuli [@leboisAreAutomaticConceptual2015; @pecherDoesPizzaPrime1998; @yeeColorlessGreenIdeas2012; @ostarekTaskdependentCausalRole2017; @connellWeKnowWhat2016; @garciaTimeFaceLanguage2020; @shebaniWhatImpairedSpatial2021; @vitaleNeuralInhibitionNetwork2021; @vukovicPrimaryMotorCortex2017; @wangSocialEmotionDimensional2021]. Further evidence for the contextual dependency of the interplay was found by @riccardiDissociatingActionAbstract2019, who investigated the comprehension of action verbs and abstract verbs in left-hemisphere stroke patients, finding that the processing of action concepts relied more heavily on sensory-motor areas. Furthermore, studies have suggested that even abstract concepts may be partially grounded in modality-specific domains such as emotion, sociality and interoception [@concaSearchDifferentCategories2021; @connellInteroceptionForgottenModality2018; @diveicaQuantifyingSocialSemantics2022; @kousta2011a; @vigliocco2014a; @wangSocialEmotionDimensional2021; @borghiAbstractConceptsExternal2022]. 

However, other research has curtailed the importance of the embodiment system [@mahonCriticalLookEmbodied2008; @bottiniConcretenessAdvantageLexical2021; @garceaPreservedToolKnowledge2013; @guntherSymbolGroundingDirect2018; @guntherLimitsAutomaticSensorimotor2021; @montero-melisNoEvidenceEmbodiment2022; @vannuscorpsPersistentSparingAction2016]. For instance, studies have found that lesions to motor brain areas did not systematically impair the processing of action concepts in language [@papeoActionPerformanceActionword2010; @negriWhatRoleMotor2007]. Furthermore, behavioural studies from the past decade have begun constraining the role of perceptual simulation. For instance, @louwerseTasteWordsLinguistic2011 found that perceptual simulation was more important late in the time course of property verification [also see @bernabeu2017a]. In another study, @connellSeeHearWhat2014 found that the auditory information in words is relevant for reading aloud but not so much for word identification. In conclusion, the language and the embodiment systems are complementary to each other [@andrewsIntegratingExperientialDistributional2009; @dedeyneVisualAffectiveMultimodal2021; @wangNeuralRepresentationAbstract2010]. 

By this point, it is fitting to take a step back and reconsider our toolkit. The terms 'linguistic' and 'embodied' provide the building blocks for the study of a more involved phenomenon, as with other dichotomies used in psychology [e.g., @kahnemanThinkingFastSlow2011; @paivioMentalRepresentationsDual1990]. Particularly noteworthy is the term 'embodied', which encompasses sensory, motor, affective and social information [@borghiWordsSocialTools2019; @newcombeEffectsEmotionalSensorimotor2012; @zwaanTwoChallengesEmbodied2021]. The division between language and embodiment has provided fruitful avenues for research and yielded a prolific output over the past two decades [@connell2019a]. To this day, there are many open questions, as demonstrated in a set of research questions put forth by @bernabeu2021a.^[The pregistration in @bernabeu2021a had to be sidelined due to project adjustments required during the Covid-19 pandemic. We hope that the research questions laid out in this preregistration inspire future research.] However, with more than two decades of history, it may be pertinent to appraise this division and consider alternatives. First, we know that the categories we have in our research toolkit may be a bit arbitrary [@tulvingAreThere2562007]. Second, cognitive science research needs to be open to change. In a recent discussion, @michelOvercomingModalAmodal2021 suggested working towards a continuous construal of language and embodiment in conceptual processing. I am sympathetic to this view, as continuums---that is, the use of gradual, continuous measures---often outperform categorical divisions in science. For instance, consider the move from categorical factors to continuous variables [@lynottModalityExclusivityNorms2009; @petilli2021a]. Part of the reason for the advantage of continuous measures probably lies in the fact that they involve more data, thus offering greater precision. At the same time, however, taking the leap advocated by Michel will practically require reframing the entire field. I look forward to following such a development in the future. However, in the present work, I adhere to the language-embodiment division. Within this framework, I have investigated how the interplay between language and sensorimotor simulation is reflected at various levels of the experimental structure---namely, at the levels of individuals, words and tasks.

One of the core reasons why it is important to investigate language and embodiment is the optimality of scientific theories, classically epitomised by Occam's razor. Occam's razor represents the desirability of concise theories. Put concretely: if one single mechanism could explain a cognitive process, only one mechanism should be used. @galleseBrainConceptsRole2005 were among the first to articulate the Occam's razor argument within the present topic. The authors argued: 'In short, we think there is an Occam’s Razor argument here. The modality-neutral structure is just not needed.' (p. 468). Gallese and Lakoff wrote that in 2005. Importantly, since then, a sizable amount of evidence has challenged the role of embodiment [@hickokMythMirrorNeurons2014], and other evidence has favoured the 'hybrid' theory, as reviewed above.   

Indeed, as reviewed above, research has profusely investigated how language and embodiment interact as a function of the concreteness of concepts and the semantic depth required by the context. In contrast, the role of individual differences has received less attention. Furthermore, most of these studies have investigated how individual differences interact with either language or sensorimotor simulation. For instance, @pexman2018a found that higher-vocabulary individuals were more sensitive to task-relevant information, such as word concreteness, when performing a task that required classifying words as abstract or concrete. Similarly, research has found that physical expertise and perceptual biases are associated with differences in the mental simulation of meaning [@beilockSportsExperienceChanges2008; @calvo-merinoActionObservationAcquired2005; @vukovic2015a]. In spite of the advancements, there is room for the investigation of further combinations, such as the way in which vocabulary knowledge interacts with both language-based information and vision-based information.


## The present thesis

In Chapter 1 (Study 1), I will describe a study to which contributed at the beginning of my PhD [@chenInvestigatingObjectOrientation2018a]. I contributed theoretical and methodological suggestions from an early stage, contributed data collected from 50 participants at Lancaster University, and then contributed to the reporting. From now, I look forward to contributing to the latest revisions of this Stage II Registered Report, which was conditionally accepted in Psychonomic Bulletin & Review. 

In Chapter 2 (Study 2), I describe three studies in computational psycholinguistics. The studies are grouped into one following the format of previous multi-part studies that revisited existing data sets [e.g., @wingfieldUnderstandingRoleLinguistic2022], as we do in these three studies.

Chapter 1 and Chapter 2 both investigate the role of sensorimotor simulation in conceptual processing and both probe into the role of individual differences, among other topics. In Chapter 1, this goal is pursued by focussing on an influential finding, the object orientation effect. In Chapter 2, the scope moves to more basic tasks of semantic and lexical processing, which are used to study both language and sensorimotor simulation. Both chapters involve many more ramifications, and I hope you enjoy diving into them next.



